### PR TITLE
Debugging Map Visualization 

### PR DESCRIPTION
**Pull request by wyawen**
map couldn't be generated- we were using `Filtered high accuracy map visualization (moving).ipynb` to debug this.

### CODE REVIEW

**Comment by shankari** [comment]
Can you remove the checkpoints? They make it very hard to review the changes.

```
$ pwd
bash-3.2$ pwd
.../data-collection-eval
$ git rm -r --cached .ipynb
```

**Comment by wyawen** [comment]
sorry! I didn't notice those were included.... I will remove them and then create a pull request again

**Comment by wyawen** [comment]
just removed all checkpoints, could you check again?

**Comment by shankari** [comment]
High level comments:
- just to make reviewing easier, it would be good if you could split into pull requests for:
  - new ipython notebooks
  - new script to parse from the battery manager output
  - changes to get maps to work
- if you haven't changed any existing notebooks, merely run them again, can you remove them from the pull request? The diffs are too large to see and I don't know what has changed.
- remove `.DS_Store` directories

**Comment by shankari** [comment]
Hm, it looks like the changes were committed to master, so it will be hard for you to generate a new pull request.

**Comment by wyawen** [comment]
Sorry for the late reply! I just saw this.
and yea.. I already committed all the changes to master. But I think the only important changes regarding map generation are found in `Filtered high accuracy map visualization (moving).ipynb`. 
Other changes were made in e-mission-server, I have created a pull request for that (which only includes the changes we made today). Taking look at that should help?

**Pull request closed without merging**
